pipeline:
  identifier: Build_Yashvanth2402_devsecops_demo_1753938224238
  name: Build devsecops-demo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: devsecops
        repoName: Yashvanth2402/devsecops-demo
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    shell: Sh
                    image: node:20
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: sonar_scan
                  name: SonarCloud Scan
                  type: Run
                  spec:
                    shell: Sh
                    image: sonarsource/sonar-scanner-cli:latest
                    envVariables:
                      SONAR_TOKEN: <+secrets.getValue("sonar_token")>
                    command: |
                      sonar-scanner \
                        -Dsonar.organization=yashvanth2402 \
                        -Dsonar.projectKey=Yashvanth2402_microservices-demo \
                        -Dsonar.sources=. \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.token=$SONAR_TOKEN
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    caching: true
                    connectorRef: <+input>
                    repo: yashvanth2402/sample
                    tags:
                      - latest
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
